export const RESET_FETCH_RESOURCE = "RESET_FETCH_RESOURCE";
export const FETCH_RESOURCES_SUCCESS = "FETCH_RESOURCES_SUCCESS";
export const FETCH_RESOURCES_FAIL = "FETCH_RESOURCES_FAIL";
export const FETCH_RESOURCES_LOADING = "FETCH_RESOURCES_LOADING";
export const NOTIFY = "NOTIFY";

export const GET_EMPLOYEE = "GET_EMPLOYEE";
export const GET_EMPLOYEE_INFO = "GET_EMPLOYEE_INFO";
export const GET_EMPLOYEE_PROFILE = "GET_EMPLOYEE_PROFILE";
export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const GET_EMPLOYEE_LIST = "GET_EMPLOYEE_LIST";
export const GET_EMPLOYEE_STATISTIC = "GET_EMPLOYEE_STATISTIC";
export const GET_EMPLOYEE_EXPIRED_STATISTIC = "GET_EMPLOYEE_EXPIRED_STATISTIC";
export const FETCH_EMPLOYEE_LOADING = "FETCH_EMPLOYEE_LOADING";

export const GET_FACTORY_LIST = "GET_FACTORY_LIST";
export const GET_FACTORY = "GET_FACTORY";
export const GET_FACTORY_INFO = "GET_FACTORY_INFO";
export const UPDATE_FACTORY = "UPDATE_FACTORY";

export const GET_DEPARTMENT_LIST = "GET_DEPARTMENT_LIST";
export const GET_DEPARTMENT = "GET_DEPARTMENT";
export const GET_DEPARTMENT_INFO = "GET_DEPARTMENT_INFO";
export const UPDATE_DEPARTMENT = "UPDATE_DEPARTMENT";

export const GET_LINE_LIST = "GET_LINE_LIST";
export const GET_LINE = "GET_LINE";
export const GET_LINE_INFO = "GET_LINE_INFO";

export const GET_GROUP_LIST = "GET_GROUP_LIST";
export const GET_GROUP = "GET_GROUP";
export const GET_GROUP_INFO = "GET_GROUP_INFO";

export const GET_CITY_LIST = "GET_CITY_LIST";
export const GET_NATION_LIST = "GET_NATION_LIST";

export const GET_CURRENT_CONTRACT = "GET_CURRENT_CONTRACT";
export const GET_CONTRACTS_EMPLOYEEID = "GET_CONTRACTS_EMPLOYEEID";
export const GET_CONTRACT_DETAIL = "GET_CONTRACT_DETAIL";
export const GET_CONTRACT_LIST = "GET_CONTRACT_LIST";

export const GET_JOB_LIST = "GET_JOB_LIST";

export const GET_POSITION_LIST = "GET_POSITION_LIST";

export const GET_INSURANCE_EMPLOYEEID = "GET_INSURANCE_EMPLOYEEID";
export const GET_INSURANCE_DETAIL = "GET_INSURANCE_DETAIL";
export const CREATE_INSURANCE = "CREATE_INSURANCE";
export const UPDATE_INSURANCE = "UPDATE_INSURANCE";

export const GET_AREA_LIST = "GET_AREA_LIST";

export const FETCH_WORKING_TIME_LOADING = "FETCH_WORKING_TIME_LOADING";
export const GET_LEAVE_MANAGAMENT = "GET_LEAVE_MANAGAMENT";
export const GET_OT_ORDER = "GET_OT_ORDER";
export const GET_OT_ORDER_CONFIRM = "GET_OT_ORDER_CONFIRM";
export const GET_OT_ORDER_EMPLOYEE = "GET_OT_ORDER_EMPLOYEE";
export const GET_IMPORTED_OT_ORDER = "GET_IMPORTED_OT_ORDER";
export const GET_OT_CONFIRM1 = "GET_OT_CONFIRM1";
export const GET_WORKING_SHIFT = "GET_WORKING_SHIFT";
export const GET_REGULARTIME_OT = "GET_REGULARTIME_OT";
export const GET_DAILY_WORKING_TIME = "GET_DAILY_WORKING_TIME";

export const ADD_IMPORTED_MODULE = "ADD_IMPORTED_MODULE";
export const GET_IMPORT_LOG = "GET_IMPORT_LOG";

export const GET_WORKSHIFT_LIST = "GET_WORKSHIFT_LIST";
export const GET_WORKSHIFT_SHIFTID = "GET_WORKSHIFT_SHIFTID";
export const GET_WORKSHIFT_LIST_OT_ORDER = "GET_WORKSHIFT_LIST_OT_ORDER";

export const GET_ALLOWANCE_EMPLOYEEID = "GET_ALLOWANCE_EMPLOYEEID";
export const GET_ALLOWANCE_DETAIL = "GET_ALLOWANCE_DETAIL";
export const GET_ALLOWANCE_LIST = "GET_ALLOWANCE_LIST";

export const GET_WORKINGINFO_WORKSHIFT = "GET_WORKINGINFO_WORKSHIFT";
export const GET_WORKINGINFO_WORKSHIFT_DETAIL =
  "GET_WORKINGINFO_WORKSHIFT_DETAIL";
export const GET_EMPLOYEE_WORKING_SHITFT = "GET_EMPLOYEE_WORKING_SHITFT";

export const GET_MATERNITY_EMPLOYEEID = "GET_MATERNITY_EMPLOYEEID";
export const GET_MATERNITY_DETAIL = "GET_MATERNITY_DETAIL";

export const GET_CHILDLIST_EMPLOYEEID = "GET_CHILDLIST_EMPLOYEEID";
export const GET_CHILDLIST_DETAIL = "GET_CHILDLIST_DETAIL";

export const GET_DISCIPLINE_EMPLOYEEID = "GET_DISCIPLINE_EMPLOYEEID";
export const GET_DISCIPLINE_DETAIL = "GET_DISCIPLINE_DETAIL";
export const GET_DISCIPLINE_LIST = "GET_DISCIPLINE_LIST";

export const GET_USER_LIST = "GET_USER_LIST";

export const GET_WORKINGTIMELIST_EMPLOYEEID_BYDATE =
  "GET_WORKINGTIMELIST_EMPLOYEEID_BYDATE";
export const GET_WORKINGTIMELIST_EMPLOYEEID_BYMONTH =
  "GET_WORKINGTIMELIST_EMPLOYEEID_BYMONTH";
export const GET_WORKINGTIMEDATE_DETAIL = "GET_WORKINGTIMEDATE_DETAIL";
export const GET_WORKING_TIME_STATISTIC = "GET_WORKING_TIME_STATISTIC";
export const GET_WORKINGTIME_SALARY_STATISTIC =
  "GET_WORKINGTIME_SALARY_STATISTIC";

export const GET_REGULARTIMEOT_DETAIL = "GET_REGULARTIMEOT_DETAIL";
export const GET_UPDATE_REGULARTIMEOT = "GET_UPDATE_REGULARTIMEOT";

export const GET_UNIFORM = "GET_UNIFORM";
export const GET_UNIFORM_INFO = "GET_UNIFORM_INFO";

export const GET_RESIGNED_EMPLOYEEID = "GET_RESIGNED_EMPLOYEEID";
export const GET_UNIFORM_LIST = "GET_UNIFORM_LIST";
export const UPDATE_UNIFORM = "UPDATE_UNIFORM";

export const GET_STATISTICS_FACTORY = "GET_STATISTICS_FACTORY";
export const GET_STATISTICS_FACTORY_LIST = "GET_STATISTICS_FACTORY_LIST";
export const GET_STATISTICS_FACTORY_INFO = "GET_STATISTICS_FACTORY_INFO";

export const GET_STATISTICS_WORKINGTIME = "GET_STATISTICS_WORKINGTIME";
export const GET_STATISTICS_WORKINGTIME_LIST =
  "GET_STATISTICS_WORKINGTIME_LIST";
export const GET_STATISTICS_WORKINGTIME_INFO =
  "GET_STATISTICS_WORKINGTIME_INFO";

export const GET_MEAL = "GET_MEAL";
export const GET_MEAL_INFO = "GET_MEAL_INFO";
export const GET_MEAL_LIST = "GET_MEAL_LIST";
export const UPDATE_MEAL = "UPDATE_MEAL";

export const GET_CHANGE_WORKING_REASON = "GET_CHANGE_WORKING_REASON";
export const GET_CHANGE_WORKING_REASON_INFO = "GET_CHANGE_WORKING_REASON_INFO";
export const GET_CHANGE_WORKING_REASON_LIST = "GET_CHANGE_WORKING_REASON_LIST";
export const UPDATE_CHANGE_WORKING_REASON = "UPDATE_CHANGE_WORKING_REASON";

export const GET_WORKINGSHIFT_ADJUSTMENT = "GET_WORKINGSHIFT_ADJUSTMENT";
export const GET_WORKINGSHIFT_ADJUSTMENT_INFO =
  "GET_WORKINGSHIFT_ADJUSTMENT_INFO";
export const GET_WORKINGSHIFT_ADJUSTMENT_LIST =
  "GET_WORKINGSHIFT_ADJUSTMENT_LIST";
export const UPDATE_WORKINGSHIFT_ADJUSTMENT = "UPDATE_WORKINGSHIFT_ADJUSTMENT";

export const GET_CONTRACTTYPE = "GET_CONTRACTTYPE";
export const GET_CONTRACTTYPE_INFO = "GET_CONTRACTTYPE_INFO";
export const GET_CONTRACTTYPE_LIST = "GET_CONTRACTTYPE_LIST";
export const UPDATE_CONTRACTTYPE = "UPDATE_CONTRACTTYPE";

export const GET_POSITION = "GET_POSITION";
export const GET_POSITION_INFO = "GET_POSITION_INFO";
export const UPDATE_POSITION = "UPDATE_POSITION";

export const GET_CHILDREN = "GET_CHILDREN";
export const GET_CHILDREN_INFO = "GET_CHILDREN_INFO";
export const GET_CHILDREN_LIST = "GET_CHILDREN_LIST";
export const UPDATE_CHILDREN = "UPDATE_CHILDREN";

export const GET_JOB = "GET_JOB";
export const GET_JOB_INFO = "GET_JOB_INFO";
// export const GET_JOB_LIST = "GET_JOB_LIST";
export const UPDATE_JOB = "UPDATE_JOB";

export const GET_MONTHSALARY_LIST = "GET_MONTHSALARY_LIST";
export const GET_MONTHSALARY_DETAIL = "GET_MONTHSALARY_DETAIL";
export const FETCH_SALARY_LOADING = "FETCH_SALARY_LOADING";
export const GET_SALARY_BYEMPLOYEEID_AND_MONTH =
  "GET_SALARY_BYEMPLOYEEID_AND_MONTH";
export const GET_SALARY_BYEMPLOYEEID_AND_DATE =
  "GET_SALARY_BYEMPLOYEEID_AND_DATE";
export const GET_SALARY_DESCRIPTION_LIST_BYDATE =
  "GET_SALARY_DESCRIPTION_LIST_BYDATE";
export const GET_SALARY_STATISTIC_BY_YEAR = "GET_SALARY_STATISTIC_BY_YEAR";
export const GET_SALARY_STATISTIC_BY_2YEAR = "GET_SALARY_STATISTIC_BY_2YEAR";

export const GET_ROLE = "GET_ROLE";
export const GET_ROLE_BY_ID = "GET_ROLE_BY_ID";
export const GET_ROLE_LIST = "GET_ROLE_LIST";
export const GET_ROLE_INFO = "GET_ROLE_INFO";
export const UPDATE_ROLE = "UPDATE_ROLE";

export const GET_PERMISSIONS = "GET_PERMISSIONS";
export const GET_PERMISSIONS_INFO = "GET_PERMISSIONS_INFO";
export const GET_PERMISSIONS_LIST = "GET_PERMISSIONS_LIST";
export const GET_LISTADMIN = "GET_LISTADMIN";
export const GET_ADMINBYID = "GET_ADMINBYID";

export const GET_USER = "GET_USER";
export const GET_USER_INFO = "GET_USER_INFO";
export const UPDATE_USER = "UPDATE_USER";
export const GET_BLACKLIST = "GET_BLACKLIST";
export const GET_BLACKLIST_DETAIL = "GET_BLACKLIST_DETAIL";
export const GET_BLACKLIST_EMPLOYEEID = "GET_BLACKLIST_EMPLOYEEID";
export const GET_CHECKBLACKLIST = "GET_CHECKBLACKLIST";

export const UPLOAD_FILE = "UPLOAD_FILE";

export const GET_CALENDAR = "GET_CALENDAR";
export const GET_CALENDAR_INFO = "GET_CALENDAR_INFO";
export const GET_CALENDAR_LIST = "GET_CALENDAR_LIST";
export const UPDATE_CALENDAR = "UPDATE_CALENDAR";

export const GET_DAY_OFF = "GET_DAY_OFF";

export const GET_DEPENDENT_PERSON = "GET_DEPENDENT_PERSON";

export const GET_TIME_IN_OUT_IN_SHIFT = "GET_TIME_IN_OUT_IN_SHIFT";

export const GET_DAILY_WORKING_TIME_INFO = GET_DAILY_WORKING_TIME_INFO;

export const GET_TIMEINTIMEOUTSHIFT = "GET_TIMEINTIMEOUTSHIFT";
export const GET_TIMEINTIMEOUTSHIFT_INFO = "GET_TIMEINTIMEOUTSHIFT_INFO";
export const GET_TIMEINTIMEOUTSHIFT_LIST = "GET_TIMEINTIMEOUTSHIFT_LIST";
export const UPDATE_TIMEINTIMEOUTSHIFT = "UPDATE_TIMEINTIMEOUTSHIFT";

export const GET_SALARYPERCENTAGE = "GET_SALARYPERCENTAGE";
export const GET_SALARYPERCENTAGE_INFO = "GET_SALARYPERCENTAGE_INFO";
export const GET_SALARYPERCENTAGE_LIST = "GET_SALARYPERCENTAGE_LIST";
export const UPDATE_SALARYPERCENTAGE = "UPDATE_SALARYPERCENTAGE";

export const GET_NEW_NOTIFICATION = "GET_NEW_NOTIFICATION";
